### ISSUE TITLE
Add a formal and appealing Color Palette to the app 

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#2]
#### Project Description:
The PES Buzz app is a user-friendly and essential tool designed to keep the college community informed about the latest events, announcements, and happenings on campus. This uncomplicated yet highly practical app offers an easy and efficient way to stay updated.

#### Description:
Improve the color palette of the PES Buzz app to create a more visually appealing and engaging design.

#### Tasks:

1. Update the primary color to give the app a fresh look.
2. Adjust the background color for better contrast and readability.
3. Define color schemes for various UI elements, ensuring consistency.

#### Acceptance Criteria:

- The app's color palette is updated to enhance the visual appeal.
- Colors are consistent and provide a pleasing user experience.
- The color changes align with the app's branding and purpose.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - event_detail_screen.dart
  - models/
    - news_item_model.dart
  - services/
    - news_item_services.dart
  - widgets/
    - news_item_card.dart
  - main.dart
- README.md

```

**Comment by shashank16sundar** [comment]
I can work on this issue @ShubhKanodia
