### ISSUE TITLE
Change AppBar, Add User Login/Date/App Logo

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#21]
---
issue: **Change AppBar, Add User Login/Date/App Logo**
description: 
The PES Buzz app is undergoing several enhancements. This issue addresses multiple improvements. It involves changing the app bar, adding user login functionality, and integrating a date/app logo to enhance the overall user experience.

**Tasks:**
- Modify the app bar design to make it visually appealing and engaging.
- Implement a user login feature, allowing users to create accounts and log in securely.
- Integrate a dynamic date display in the app for real-time updates.
- Add the app logo to reinforce the app's branding and identity.

**Acceptance Criteria:**
- The app bar's design is updated and visually appealing.
- Users can create accounts, log in securely, and access personalized features.
- The app displays the current date for real-time updates.
- The app logo is integrated into the user interface.

**Definition of Done:**
- The changes are well-documented and follow Flutter best practices.
- The user login feature is secure and functional.
- The date display is accurate and responsive.
- The app logo is added to enhance branding and identity.
- The issue is reviewed and accepted for implementation.
---

This properly formatted MDX can be easily copied and pasted into your GitHub repository to create the issue. It features bold titles and organized sections for clear readability.

**Comment by shashank16sundar** [comment]
Assign me this issue @ShubhKanodia

**Comment by shashank16sundar** [comment]
I can work on this issue @ShubhKanodia
