### ISSUE TITLE
Delay Spinkit for 1 Second Before Showing the SpinKitCircle

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#26]
---
issue: **Delay Spinkit for 1 Second Before Showing the SpinkitCircle**
description:
In the PES Buzz app, there is a loading spinner (Spinkit) displayed while fetching data. To enhance the user experience, we aim to introduce a 1-second delay before showing the spinner. This slight delay will provide a smoother transition and avoid the spinner from appearing too quickly.

**Tasks:**
- Implement a 1-second delay before displaying the Spinkit spinner.
- Ensure that the spinner animation starts after the 1-second delay.
- Maintain a seamless transition and loading experience.

**Acceptance Criteria:**
- When the data fetching process begins, the app should wait for 1 second before showing the Spinkit spinner.
- The spinner animation starts smoothly after the 1-second delay.
- The 1-second delay enhances the user experience by preventing abrupt transitions.

**Definition of Done:**
- A 1-second delay is implemented before displaying the Spinkit spinner.
- The spinner animation starts smoothly after the 1-second delay.
- Testing confirms that the delay improves the loading experience.
- The issue is reviewed and accepted for implementation.
---

=

**Comment by Royalty252** [comment]
i want to solve this issue
Can you assign me ,please ??

**Comment by rajeev-goyal** [comment]
Do we have to do it for all the platforms?

**Comment by varun80042** [comment]
I'll work on this issue @ShubhKanodia
