### ISSUE TITLE
Connect app to Firebase(Cloud firestore)

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#3]
#### Project Description:
The PES Buzz app is a user-friendly and essential tool designed to keep the college community informed about the latest events, announcements, and happenings on campus. This uncomplicated yet highly practical app offers an easy and efficient way to stay updated.

#### Description:
To provide real-time news and event updates, the PES Buzz app needs to be connected to Firebase Cloud Firestore. This issue involves setting up Firestore integration to establish a connection between the app and the Firestore database.

#### Tasks:

1. Configure Firebase Cloud Firestore for the project.
2. Establish a connection between the app and Firestore.
3. Implement the basic structure for data retrieval and management from Firestore.

#### Acceptance Criteria:

- The app is successfully connected to Firebase Cloud Firestore.
- The basic Firestore setup allows for data retrieval and management.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - event_detail_screen.dart
  - models/
    - news_item_model.dart
  - services/
    - news_item_services.dart
  - widgets/
    - news_item_card.dart
  - main.dart
- README.md

```

**Comment by varun80042** [comment]
I can work on this issue
