### ISSUE TITLE
Add a Nice Splash Screen for the App

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#4]
#### Project Description:
The PES Buzz app is a user-friendly and essential tool designed to keep the college community informed about the latest events, announcements, and happenings on campus. This uncomplicated yet highly practical app offers an easy and efficient way to stay updated.

#### Description:
A splash screen is a great way to create a professional and branded introduction to the app. This issue involves adding a splash screen to the PES Buzz app that will display when the app is launched, providing a polished and engaging start to the user experience.

#### Tasks:

1. Design and implement a splash screen with branding elements that represent the PES Buzz app.
2. Ensure that the splash screen displays for a brief but engaging period.
3. Implement a smooth transition from the splash screen to the main app interface.

#### Acceptance Criteria:

- The app features a professionally designed splash screen that aligns with the app's branding.
- The splash screen displays for a short and engaging period when the app is launched.
- The transition from the splash screen to the main app interface is smooth and polished.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - event_detail_screen.dart
  - models/
    - news_item_model.dart
  - services/
    - news_item_services.dart
  - widgets/
    - news_item_card.dart
  - main.dart
- README.md

```

**Comment by shashank16sundar** [comment]
I can work on this issue @ShubhKanodia
