### ISSUE TITLE
Add TabBar to HomePage

### ISSUE THREAD

**Issue by ShubhKanodia** [dscpesu/PES-BUZZ#5]
#### Project Description:
The PES Buzz app is a user-friendly and essential tool designed to keep the college community informed about the latest events, announcements, and happenings on campus. This uncomplicated yet highly practical app offers an easy and efficient way to stay updated.

#### Description:
The PES Buzz app provides news in different categories, including "Trendy," "Sports," and specific departments or clubs. To improve user navigation and organization, this issue involves adding a tab bar that allows users to easily switch between these categories for a more user-friendly experience.

#### Tasks:

1. Implement a tab bar widget for navigating between different news categories.
2. Connect the tab bar to the corresponding data sources for each category.
3. Update the UI to display news items based on the selected category.
4. Ensure a smooth and user-friendly tab bar experience for users.

#### Acceptance Criteria:

- The app features a tab bar that allows users to navigate between different news categories.
- The tab bar is connected to the relevant data sources, ensuring accurate content display.
- Users can easily switch between categories, and the app provides a smooth and user-friendly tab bar experience.

#### Adhere to the below folder structure for reference
```
- lib/
  - screens/
    - home_screen.dart
    - event_detail_screen.dart
  - models/
    - news_item_model.dart
  - services/
    - news_item_services.dart
  - widgets/
    - news_item_card.dart
  - main.dart
- README.md

```

**Comment by varun80042** [comment]
I can work on this issue.

**Comment by JayeshYadav99** [comment]
@ShubhKandia can you tell me how can i view your web app ,because i have cloned your web folder but unable to see your web site ,please share me pesbuzz website link
